# First Class
# The pass statement is used as a placeholder for the future code. When the pass 
# statement is executed, nothing happens, but you avoid getting an error when empty 
# code is not allowed. Empty code is not allowed in loops, function definitions,
# class definitions, or in if statements.

# placeholder: marcador futuro
class Animal():
    pass

dog = Animal()
cat = Animal()
print(dog)
print(cat)